config/routes.rb
::Refinery::Application.routes.draw do

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :banners, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/banner.rb
class Banner < ActiveRecord::Base

  acts_as_indexed :fields => [:name, :url, :title, :description]

  validates :name, :presence => true
  validates_presence_of :start_date
  validates_length_of :title, :in => 0..255, :allow_nil => true
  validates_length_of :description, :in => 0..255, :allow_nil => true

  belongs_to :image
  has_and_belongs_to_many :pages

  scope :not_expired, lambda {
    banners = Arel::Table.new(Banner.table_name)
    where(banners[:expiry_date].eq(nil).or(banners[:expiry_date].gt(Time.now)))
  }
  scope :active, where(:is_active => true)
  scope :published, lambda {
    not_expired.active.where("start_date <= ?", Time.now).order(:position)
  }

end

app/controllers/admin/banners_controller.rb
module Admin
  class BannersController < Admin::BaseController

    crudify :banner,
            :title_attribute => 'name', :xhr_paging => true

  end
end

app/views/admin/banners/_actions.html.erb
<ul>
  <% if Admin::BannersController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_banners_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_banner_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::BannersController.sortable? and Banner.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Banners"),
                 admin_banners_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Banners"),
                 admin_banners_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/banners/_banner.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(banner) -%>">
  <span class='title'>
    <%= banner.name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_banner_path(banner),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_banner_path(banner),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => banner.name),
        :method => :delete %>
  </span>
</li>

app/views/admin/banners/_banners.html.erb
<%= will_paginate @banners %>
<%= render :partial => "sortable_list" %>

app/views/admin/banners/_form.html.erb
<%= form_for [:admin, @banner] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @banner,
          :include_object_name => true
        } %>

  <%= hidden_field_tag 'banner[page_ids][]' %>

  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :image -%>
    <%= render :partial => "/shared/admin/image_picker", :locals => {
          :f => f,
          :field => :image_id,
          :image => @banner.image,
          :toggle_image_display => false
        } %>
  </div>

  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title -%>
  </div>

  <div class='field'>
    <%= f.label :description -%>
    <%= f.text_field :description -%>
  </div>

  <div class='field'>
    <%= f.label :url -%>
    <%= f.text_field :url  -%>
  </div>
  
  <div class='field'>
    <%= f.label :is_active -%>
    <%= f.check_box :is_active, :checked => @banner[:is_active]  -%>
  </div>
  
  <div class='field'>
    <%= f.label :start_date -%>
    <%= f.date_select :start_date  -%>
  </div>
  
  <div class='field'>
    <%= f.label :expiry_date -%>
    <%= f.date_select :expiry_date  -%>
  </div>

  <div class="field">
    <%= f.label :pages %>
    <% for page in Page.find(:all) %>
      <div>
        <%= check_box_tag "banner[page_ids][]", page.id, @banner.pages.include?(page) %>
        <%= page.title %>
      </div>
    <% end %>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.banners.banner'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @banner.name)
              } %>
<% end -%>

app/views/admin/banners/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @banners.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'banners' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/banners/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'banner', :collection => @banners %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/banners/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/banners/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::BannersController.sortable? and Banner.count > 1 %>

app/views/admin/banners/new.html.erb
<%= render :partial => "form" %>

app/views/shared/_banner_image.html.erb
<%= image_fu(banner_image.image, '960x310#c') %>

app/views/shared/_banners.html.erb
<div id="slider">
  <% if @page.present? and @page.banners.published.present? %>
    <%= render :partial => 'shared/banner_image', :collection => @page.banners.published %>
  <% elsif @banners.present? then %>
      <%= render :partial => 'shared/banner_image', :collection => @banners %>
  <% else %>
    <!--todo: insert static images here-->
  <% end %>
</div>